-- Test data for IdeaVault

-- Insert test users
INSERT INTO users (
  id,
  email,
  username,
  full_name,
  avatar_url,
  user_type,
  verified,
  bio,
  expertise_tags,
  location,
  website_url,
  social_links,
  notification_preferences
) VALUES 
(
  '11111111-1111-1111-1111-111111111111',
  'seller1@test.com',
  'idea_seller',
  '김창업',
  'https://ui-avatars.com/api/?name=김창업&background=3b82f6&color=ffffff',
  'seller',
  true,
  '검증된 마이크로 SaaS 아이디어를 제공합니다.',
  ARRAY['SaaS', 'Startup', 'MVP'],
  '서울, 대한민국',
  'https://example.com',
  '{"linkedin": "example", "twitter": "example"}',
  '{"email": true, "push": false}'
),
(
  '22222222-2222-2222-2222-222222222222',
  'buyer1@test.com',
  'vibe_coder',
  '박개발',
  'https://ui-avatars.com/api/?name=박개발&background=22c55e&color=ffffff',
  'buyer',
  false,
  '바이브 코딩으로 빠르게 개발합니다.',
  ARRAY['React', 'Node.js', 'AI'],
  '부산, 대한민국',
  'https://github.com/example',
  '{"github": "example"}',
  '{"email": true, "push": true}'
);

-- Insert test ideas
INSERT INTO ideas (
  id,
  seller_id,
  title,
  slug,
  description,
  category,
  subcategory,
  package_type,
  price,
  currency,
  target_audience,
  revenue_model,
  implementation_difficulty,
  estimated_dev_time,
  tech_stack,
  market_size,
  validation_status,
  validation_notes,
  preview_content,
  full_content,
  files,
  view_count,
  purchase_count,
  status,
  featured,
  seo_keywords,
  published_at
) VALUES 
(
  '33333333-3333-3333-3333-333333333333',
  '11111111-1111-1111-1111-111111111111',
  'AI 기반 학습 도우미 SaaS',
  'ai-learning-assistant-saas',
  '개인 맞춤형 학습 계획을 제공하는 AI 기반 학습 도우미 플랫폼입니다. 사용자의 학습 패턴을 분석하여 최적의 학습 방법을 제안합니다.',
  'education',
  'e-learning',
  'mvp',
  350000,
  'KRW',
  '대학생, 직장인, 자기계발을 원하는 성인',
  'subscription',
  3,
  '4-6주',
  ARRAY['React', 'Node.js', 'Python', 'OpenAI API', 'PostgreSQL'],
  '중간 규모 (10만-100만 사용자)',
  'approved',
  '시장 조사 완료, 초기 사용자 피드백 긍정적',
  '이 아이디어는 개인 맞춤형 학습을 통해 학습 효율성을 높이는 것을 목표로 합니다. AI가 사용자의 학습 패턴을 분석하여...',
  '완전한 구현 가이드, 기술 스택 상세 설명, 시장 진입 전략, 수익 모델 분석이 포함되어 있습니다.',
  '{"requirements.pdf": {"url": "example.com/file1", "size": "2MB"}, "wireframes.figma": {"url": "example.com/file2", "size": "5MB"}}',
  156,
  3,
  'active',
  true,
  ARRAY['AI', '학습', 'SaaS', '교육', '맞춤형'],
  NOW()
),
(
  '44444444-4444-4444-4444-444444444444',
  '11111111-1111-1111-1111-111111111111',
  '소상공인을 위한 재고 관리 도구',
  'inventory-management-tool',
  '소규모 상점과 카페를 위한 간단하고 직관적인 재고 관리 솔루션입니다. 바코드 스캔, 자동 발주, 매출 분석 기능을 제공합니다.',
  'business',
  'inventory',
  'launch_kit',
  750000,
  'KRW',
  '소상공인, 카페 사장, 소규모 유통업체',
  'saas',
  2,
  '6-8주',
  ARRAY['Vue.js', 'Laravel', 'MySQL', 'PWA'],
  '소규모 (1만-10만 사용자)',
  'approved',
  '타겟 고객 인터뷰 완료, MVP 테스트 성공',
  '소상공인들이 겪는 재고 관리의 어려움을 해결하는 솔루션입니다. 스마트폰으로 간편하게 재고를 체크하고...',
  '완전한 비즈니스 플랜, 기술 구현 가이드, 고객 확보 전략, 마케팅 계획, 3개월 멘토링이 포함된 런치 키트입니다.',
  '{"business_plan.pdf": {"url": "example.com/file3", "size": "8MB"}, "tech_spec.docx": {"url": "example.com/file4", "size": "3MB"}}',
  89,
  1,
  'active',
  false,
  ARRAY['재고관리', '소상공인', 'B2B', 'SaaS'],
  NOW()
),
(
  '55555555-5555-5555-5555-555555555555',
  '11111111-1111-1111-1111-111111111111',
  '펫시터 매칭 플랫폼',
  'pet-sitter-matching-platform',
  '신뢰할 수 있는 펫시터와 반려동물 주인을 연결해주는 플랫폼입니다. 위치 기반 매칭, 실시간 케어 리포트, 안전 보험 시스템을 제공합니다.',
  'lifestyle',
  'pet-care',
  'idea',
  180000,
  'KRW',
  '반려동물을 키우는 직장인, 여행객',
  'commission',
  4,
  '8-10주',
  ARRAY['React Native', 'Node.js', 'MongoDB', 'Socket.io', 'Google Maps API'],
  '중간 규모 (10만-100만 사용자)',
  'approved',
  '반려동물 시장 성장세, 경쟁사 분석 완료',
  '바쁜 반려동물 주인들을 위한 신뢰할 수 있는 펫시터 매칭 서비스입니다. 지역별 검증된 펫시터를...',
  '시장 조사 리포트, 경쟁사 분석, 기본 와이어프레임, 수익 모델 설계가 포함되어 있습니다.',
  '{"market_research.pdf": {"url": "example.com/file5", "size": "4MB"}}',
  234,
  5,
  'active',
  false,
  ARRAY['펫시터', '매칭', '반려동물', '플랫폼'],
  NOW()
);